def SweetDreams
  bpm = 140
  noiseDrum = Instrument.new(bpm, NoiseOscillator.new(44100, 123.0, 0.6), [], nil, nil)
  synthBass = Instrument.new(bpm, SawtoothOscillator.new(44100, 123.0, 0.3), [1.0], nil, nil)
  voice = Instrument.new(bpm, SineOscillator.new(44100, 220.0, 0.8), [0.1, 0.4], nil, nil)
  
  drumTrack = Track.new(noiseDrum)
  24.times {
    drumTrack.notes << Note.new("", 0, 4)
    drumTrack.notes << Note.new("A", 0, 16)
    drumTrack.notes << Note.new("", 0, 16)
    drumTrack.notes << Note.new("", 0, 8)
  }
  
  bassTrack = Track.new(synthBass)
  6.times {
    bassTrack.notes << Note.new("A", 0, 16)
    bassTrack.notes << Note.new("", 1, 16)
    bassTrack.notes << Note.new("A", 1, 16)
    bassTrack.notes << Note.new("", 1, 16)
    bassTrack.notes << Note.new("A", 2, 16)
    bassTrack.notes << Note.new("", 1, 16)
    bassTrack.notes << Note.new("A", 2, 16)
    bassTrack.notes << Note.new("", 1, 16)
    bassTrack.notes << Note.new("C", 1, 16)
    bassTrack.notes << Note.new("", 1, 16)
    bassTrack.notes << Note.new("C", 2, 16)
    bassTrack.notes << Note.new("", 1, 16)
    bassTrack.notes << Note.new("A", 1, 16)
    bassTrack.notes << Note.new("", 1, 16)
    bassTrack.notes << Note.new("A", 2, 16)
    bassTrack.notes << Note.new("", 1, 16)
    bassTrack.notes << Note.new("F", 0, 16)
    bassTrack.notes << Note.new("", 1, 16)
    bassTrack.notes << Note.new("F", 0, 16)
    bassTrack.notes << Note.new("", 1, 16)
    bassTrack.notes << Note.new("F", 1, 16)
    bassTrack.notes << Note.new("", 1, 16)
    bassTrack.notes << Note.new("A", 2, 16)
    bassTrack.notes << Note.new("", 1, 16)
    bassTrack.notes << Note.new("E", 0, 16)
    bassTrack.notes << Note.new("", 1, 16)
    bassTrack.notes << Note.new("E", 0, 16)
    bassTrack.notes << Note.new("", 1, 16)
    bassTrack.notes << Note.new("E", 1, 16)
    bassTrack.notes << Note.new("", 1, 16)
    bassTrack.notes << Note.new("A", 2, 16)
    bassTrack.notes << Note.new("", 1, 16)
  }
  
  voiceTrack = Track.new(voice)
  4.times {
    voiceTrack.notes << Note.new("", 1, 1)
  }
  voiceTrack.notes << Note.new("", 1, 4)
  voiceTrack.notes << Note.new("C", 4, 8)
  voiceTrack.notes << Note.new("C", 4, 16)
  voiceTrack.notes << Note.new("", 4, 16)
  voiceTrack.notes << Note.new("C", 4, 8)
  voiceTrack.notes << Note.new("C", 4, 16)
  voiceTrack.notes << Note.new("", 4, 16)
  voiceTrack.notes << Note.new("A", 4, 4)
  voiceTrack.notes << Note.new("C", 4, 16)
  voiceTrack.notes << Note.new("C", 4, 32)
  voiceTrack.notes << Note.new("", 4, 32)
  voiceTrack.notes << Note.new("C", 4, 8)
  voiceTrack.notes << Note.new("C", 4, 16)
  voiceTrack.notes << Note.new("", 4, 16)
  voiceTrack.notes << Note.new("C", 4, 8)
  voiceTrack.notes << Note.new("B", 4, 2)
  
  voiceTrack.notes << Note.new("C", 4, 16)
  voiceTrack.notes << Note.new("C", 4, 32)
  voiceTrack.notes << Note.new("", 4, 32)
  voiceTrack.notes << Note.new("C", 4, 16)
  voiceTrack.notes << Note.new("C", 4, 32)
  voiceTrack.notes << Note.new("", 4, 32)
  voiceTrack.notes << Note.new("A", 4, 8)
  voiceTrack.notes << Note.new("C", 4, 4)
  voiceTrack.notes << Note.new("C", 4, 8)
  voiceTrack.notes << Note.new("A", 4, 16)
  voiceTrack.notes << Note.new("A", 4, 32)
  voiceTrack.notes << Note.new("", 4, 32)
  voiceTrack.notes << Note.new("A", 4, 16)
  voiceTrack.notes << Note.new("A", 4, 32)
  voiceTrack.notes << Note.new("", 4, 32)
  voiceTrack.notes << Note.new("C", 4, 8)
  voiceTrack.notes << Note.new("D", 4, 4)
  voiceTrack.notes << Note.new("D", 4, 16)
  voiceTrack.notes << Note.new("", 4, 16)
  voiceTrack.notes << Note.new("C", 4, 8)
  voiceTrack.notes << Note.new("B", 4, 8)
  voiceTrack.notes << Note.new("", 4, 8)
  voiceTrack.notes << Note.new("A", 4, 8)
  
  voiceTrack.notes << Note.new("C", 4, 16)
  voiceTrack.notes << Note.new("C", 4, 32)
  voiceTrack.notes << Note.new("", 4, 32)
  voiceTrack.notes << Note.new("C", 4, 16)
  voiceTrack.notes << Note.new("C", 4, 32)
  voiceTrack.notes << Note.new("", 4, 32)
  voiceTrack.notes << Note.new("A", 4, 8)
  voiceTrack.notes << Note.new("C", 4, 4)
  voiceTrack.notes << Note.new("C", 4, 8)
  voiceTrack.notes << Note.new("A", 4, 16)
  voiceTrack.notes << Note.new("A", 4, 32)
  voiceTrack.notes << Note.new("", 4, 32)
  voiceTrack.notes << Note.new("A", 4, 16)
  voiceTrack.notes << Note.new("A", 4, 32)
  voiceTrack.notes << Note.new("", 4, 32)
  voiceTrack.notes << Note.new("C", 4, 16)
  voiceTrack.notes << Note.new("C", 4, 32)
  voiceTrack.notes << Note.new("", 4, 32)
  voiceTrack.notes << Note.new("C", 4, 8)
  voiceTrack.notes << Note.new("C", 4, 16)
  voiceTrack.notes << Note.new("C", 4, 32)
  voiceTrack.notes << Note.new("", 4, 32)
  voiceTrack.notes << Note.new("C", 4, 8)
  voiceTrack.notes << Note.new("B", 4, 4)
  voiceTrack.notes << Note.new("", 4, 4)
  
  voiceTrack.notes << Note.new("C", 4, 4)
  voiceTrack.notes << Note.new("A", 4, 8)
  voiceTrack.notes << Note.new("C", 4, 4)
  voiceTrack.notes << Note.new("A", 4, 4)
  voiceTrack.notes << Note.new("A", 4, 8)
  voiceTrack.notes << Note.new("C", 4, 16)
  voiceTrack.notes << Note.new("C", 4, 32)
  voiceTrack.notes << Note.new("", 4, 32)
  voiceTrack.notes << Note.new("C", 4, 8)
  voiceTrack.notes << Note.new("D", 4, 8)
  voiceTrack.notes << Note.new("C", 4, 4)
  voiceTrack.notes << Note.new("B", 4, 4)

  
  s = Song.new()
  s.tracks = [drumTrack, bassTrack, voiceTrack]
  
  return s.nextSamples(s.sampleLength)
end